---
- name: Add RPM Key (Microsoft)
  rpm_key:
    state: present
    key: " {{ microsoftSigningKey }} "

- name: Add RPM Key (Mono)
  rpm_key:
    state: present
    key: " {{ monoSigningKey }} "

- name: Add YUM Repo (Microsoft)
  yum_repository:
    name: packages-microsoft-com-prod
    baseurl: " {{ microsoftYumRepo }} "
    description: Dotnet repos
  tags:
    - molecule-idempotence-notest

- name: Add YUM Repo (Mono)
  yum_repository:
    name: mono-centos8-stable
    baseurl: " {{ monoYumRepo }} "
    description: Mono repos
  tags:
    - molecule-idempotence-notest

- name: Install dotnet and mono
  dnf:
    name: ['dotnet-sdk-2.1', 'dotnet-sdk-3.1', 'dotnet-sdk-5.0',
    'aspnetcore-runtime-2.1', 'aspnetcore-runtime-3.1', 'aspnetcore-runtime-5.0',
    'mono-complete']