---
- name: Install prereqs
  dnf:
    name: ['autoconf', 'sysconftool', 'libsndfile-devel', 'alsa-lib-devel', 'fftw-devel']

- name: Install tools
  dnf:
    name: ['hackrf', 'gqrx', 'urh']

- name: Check if already installed
  command: ls -alh /usr/local/include/liquid
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no

- name: clone repo
  git: repo=https://github.com/jgaeddert/liquid-dsp.git dest=/usr/src/liquid-dsp/ depth=1
  when: is_installed.rc == 2

- name: make, build, install
  shell: cd /usr/src/liquid-dsp && ./bootstrap.sh && ./configure && make && make install
  when: is_installed.rc == 2

# sigutils
- name: Check if already installed
  command: ls -alh /usr/src/
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no

- name: clone repo
  git: repo=https://github.com/BatchDrake/sigutils.git dest=/usr/src/sigutils/ depth=1
  when: is_installed.rc == 2

- name: make, build, install
  shell: autoreconf -fvi && ./configure && make
  when: is_installed.rc == 2

