---
- name: Install prereqs
  dnf:
    name: ['readline-devel', 'arm-none-eabi-gcc-cs', 'arm-none-eabi-newlib', 'avr-libc', 'pcsc-lite', 'pcsc-lite-devel']

- name: Download
  git:
    repo: https://github.com/Proxmark/proxmark3.git
    dest: /opt/proxmark3
    depth: 1
  register: u

- name: Compile and install
  command: " {{ item }} chdir=/opt/proxmark3"
  with_items:
    - make
  when: u.changed


- file:
    src: /opt/proxmark3/client/proxmark3
    dest: /usr/bin/proxmark3
    state: link
