---
- name: Install prereqs
  dnf:
    name: ['git', 'make', 'gcc', 'gcc-c++', 'arm-none-eabi-gcc-cs', 'arm-none-eabi-newlib', 'readline-devel', 'qt5-qtbase-devel', 'libatomic']

- name: Download
  git:
    repo: https://github.com/RfidResearchGroup/proxmark3.git
    dest: /opt/proxmark3
    depth: 1
  register: u

- name: Compile and install
  command: " {{ item }} chdir=/opt/proxmark3"
  with_items:
    - make clean
    - make all -j
  when: u.changed


- file:
    src: /opt/proxmark3/client/proxmark3
    dest: /usr/bin/proxmark3
    state: link
