---
- hosts: all
  become: yes
  become_user: root

  roles:
    - uptodate
    - common
    - afl
    - bazel
    - dotnet
    - exploitdb
    - floss
    - fuzzlists
    - kubectl
    - libvirt
    - molecule
    - packer
    - radamsa
    - metasploit
    - rust
    - recon
    - sdr
    - terraform
    - vault
    - vagrant
    - vscode
