---
- name: Install common
  dnf:
    name: ['screen', 'vim-enhanced', 'aria2', 'remmina',
    'fedora-workstation-repositories']

- name: Enable Google Chrome in Fedora-Workstation-Repositories
  dnf:
    name: google-chrome
    enablerepo: google-chrome
    state: present

- name: Install Chrome
  dnf:
    name: ['google-chrome-stable']

- name: Enable Signal Desktop Copr Repository
  yum_repository:
    name: signal
    description: Copr repo for Signal-Desktop owned by luminoso
    baseurl: https://download.copr.fedorainfracloud.org/results/luminoso/Signal-Desktop/fedora-$releasever-$basearch/
    gpgcheck: yes
    gpgkey: https://download.copr.fedorainfracloud.org/results/luminoso/Signal-Desktop/pubkey.gpg

- name: Install signal-desktop
  dnf:
    name: ['signal-desktop']

- name: Add kubernetes repo
  yum_repository:
    name: kubernetes
    description: kubernetes repo hosted off google
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install kubectl
  dnf:
    name: kubectl
    state: installed
