---
- name: Add vscode repo
  yum_repository:
    name: vscode
    description: Visual Studio Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install VSCode
  dnf:
    name: code
    state: latest
    update_cache: yes
