---
- name: Ensure VSCode repo exists
  yum_repository:
    name: vscode
    description: Visual Studio Code repo
    baseurl: " {{ yumRepoUrl }} "
    gpgkey: " {{ yumRepoGpgKey }} "
    gpgcheck: yes
  tags:
    - molecule-idempotence-notest

- name: Install VSCode
  dnf:
    name: code
    state: installed
