---
- name: Install common
  dnf:
    name: ['dnf-plugins-core']

- name: Enable bazel
  command: dnf copr enable vbatts/bazel -y
  changed_when: no
  args:
    warn: false

- name: Install bazel
  dnf:
    name: ['bazel']