---
wordlistPath: /opt/wordlists
ffufGitRepo: github.com/ffuf/ffuf
ffufPath: ~/go/bin/ffuf
goBusterReleaseUrl: https://github.com/OJ/gobuster/releases/download/v3.1.0/gobuster-linux-amd64.7z
goBusterPath: /usr/local/bin/gobuster
nmapGitRepo: https://github.com/nmap/nmap
nmapPath: /usr/src/nmap
nmapHash: 4b46fa7097673f157e7b93e72f0c8b3249c54b4c
masscanGitRepo: https://github.com/robertdavidgraham/masscan.git
masscanPath: /usr/src/masscan
masscanHash: 41bd24e475f17c63c2bf721c41e5ec0aad1cea18
gauGitRepo: github.com/lc/gau
gauPath: ~/go/bin/gau