---
- name: Get latest build of packer
  shell:  curl -s https://checkpoint-api.hashicorp.com/v1/check/packer | jq -rc '.current_download_url + "packer_" + .current_version + "_linux_amd64.zip"' 
  register: latest_url
  # Needed due to get_url module not doing enough here, slash dodgy sed requirements
  args:
    warn: false

- name: Check if already installed
  command: ls -alh /usr/local/bin/packer
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no

- name: Version Check
  shell: packer version | grep "out of date"
  register: newbuild
  failed_when: no
  when: is_installed.rc == 0

- name: Install packer
  unarchive: src={{latest_url.stdout}}  dest=/usr/local/bin/ copy=no
  when: (is_installed.rc == 2) or (newbuild.rc == 130)
