---
- name: Install libvirt/virt-manager
  dnf: 
    name: ['libvirt-devel', '@virtualization']

- name: Add user to libvirt group
  user:
    name: "{{ lookup('env','USERNAME') }}"
    groups: libvirt
    append: yes
  when: "{{ lookup('env','USERNAME') | length > 0}}"

