---
- name: Check if already installed
  command: ls -alh {{ ffufPath }}
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no
  become: no

- name: Get ffuf # noqa 301
  command: go get {{ ffufGitRepo }}
  become: no
  when: is_installed.rc == 2