---
- name: Check if already installed
  command: ls -alh {{ gauPath }}
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no
  become: no

- name: Get gau # noqa 301
  command: go get {{ gauGitRepo }}
  become: no
  when: is_installed.rc == 2