---
- name: Check if already installed
  command: ls -alh {{ goBusterPath }}
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no
  become: no

- name: Get gobuster # noqa 301
  command: go get {{ goBusterGitRepo }}
  become: no
  when: is_installed.rc == 2