---
- name: Ensure unzip installed
  dnf:
    name: ['p7zip']

- name: Check if already installed
  command: ls -alh {{ goBusterPath }}
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no
  become: no

# We can't use unarchive because it will always use unarchive / gtar
# Neither of which handle 7z files
- name: Download GoBuster
  get_url:
    url: https://github.com/OJ/gobuster/releases/download/v3.1.0/gobuster-linux-amd64.7z
    dest: /tmp/
  when: is_installed.rc == 2

- name: extract
  shell: 7za x gobuster-linux-amd64.7z && mv gobuster-linux-amd64/gobuster {{ goBusterPath }} && chmod 0755 {{ goBusterPath }}
  args:
    chdir: /tmp
  when: is_installed.rc == 2