---
# We want golang and gcc for both gobuster and nmap
- name: Include golang
  include_role:
    name: dev
    tasks_from: golang

- name: Include gcc
  include_role:
    name: dev
    tasks_from: gcc

- name: Masscan
  include_tasks: masscan.yml

- name: nmap
  include_tasks: nmap.yml

- name: gobuster
  include_tasks: gobuster.yml

- name: ffuf
  include_tasks: ffuf.yml

- name: wordlists
  include_tasks: wordlists.yml

- name: gau
  include_tasks: gau.yml