---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Create folder for test
    file:
      path: /usr/local/src/dotnet-test
      state: directory
      mode: 0644
  - name: Copy Hello.csproj
    copy:
      src: files/Hello.csproj
      dest: /usr/local/src/dotnet-test/
      mode: 0644
  - name: Copy Program.cs
    copy:
      src: files/Program.cs
      dest: /usr/local/src/dotnet-test/
      mode: 0644
  - name: dotnet restore # noqa 301
    command:
      cmd: dotnet restore
      chdir: /usr/local/src/dotnet-test/
  - name: dotnet msbuild # noqa 301
    command:
      cmd: dotnet msbuild
      chdir: /usr/local/src/dotnet-test/
  - name:  Test run binary # noqa 301
    command:
      cmd: dotnet bin/Debug/netcoreapp5.0/Hello.dll
      chdir: /usr/local/src/dotnet-test/
    register: run_result
  - name: Assert
    assert:
      that: run_result.stdout == "Hello World!"