---
- name: Copy GPG key
  copy:
    src: files/RPM-GPG-KEY-Metasploit
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-Metasploit
    mode: 0644

- name: Add repository
  yum_repository:
    name: metasploit-framework
    description: Metasploit
    baseurl: http://downloads.metasploit.com/data/releases/metasploit-framework/rpm
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Metasploit

- name: Install metasploit
  dnf:
    name: ['metasploit-framework']
