---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Test pull and build using golang # noqa 301
    command:
      cmd: go get github.com/golang/example/hello
    become: no
  - name:  Test run binary # noqa 301
    command:
      cmd: ~/go/bin/hello
    register: run_result
    become: no