---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Test pull and build using golang # noqa 301
    command:
      cmd: go get golang.org/x/example/hello
    become: no
  - name:  Test run gobuster # noqa 301
    command:
      cmd: ~/go/bin/hello
    register: run_result
    become: no
  - name:  Test run bazelisk # noqa 301
    command:
      cmd: ~/go/bin/bazelisk
    register: run_result
    become: no
