---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/fedora:35
    pre_build_image: true
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: prepare.yml
    converge: ../../site.yml
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: ansible
