---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: docker.io/fedora:33
    pre_build_image: true
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: prepare.yml
    converge: ../../site.yml
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: ansible
