---
- name: Install radamsa
  dnf:
    name: ['radamsa']

- name: Install prereqs for afl
  dnf:
    name: [ 'gnuplot', 'libtool', 'make', 'automake', 'bison', 'glib2', 'glib2-devel', 'msgpack-devel']

- name: Download and unpack
  unarchive:
    src: " {{ aflUrl }} "
    dest: /usr/src/
    remote_src: yes
    mode: 0755
  notify: Compile and install afl
  retries: 3 # Have retries on this, as sometimes Halvar's site seems to be a bit iffy.
  # That or github action runners are trash.

- name: Enable core dumps # noqa 301
  shell: echo core > /proc/sys/kernel/core_pattern
  # "molecule-notes" is what we use when testing the playbook with end to end
  # when it's being 'tested'. it's in a docker container and /proc/sys is read-only
  tags:
    - molecule-notest
