---
- name: Check if already installed
  command: ls -alh /usr/bin/terraform
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no

- name: Install
  unarchive: src=https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip dest=/usr/bin/  copy=no
  when: is_installed.rc == 2

- name: Check if already installed
  command: ls -alh /usr/bin/terraform-inventory
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no

- name: Install
  unarchive: src=https://github.com/adammck/terraform-inventory/releases/download/v0.7-pre/terraform-inventory_v0.7-pre_linux_amd64.zip dest=/usr/bin/  copy=no
  when: is_installed.rc == 2

