---
- name: Install prereqs
  dnf: 
    name: ['libini_config-devel', 'libseccomp-devel']

- name: Download
  git:
    repo: https://github.com/zardus/preeny.git
    dest: /usr/src/preeny
  register: u

- name: Compile and install
  command: " {{ item }} chdir=/usr/src/preeny"
  with_items:
    - make
  when: u.changed
