---
- name: Register testing file
  stat:
    path: "/tmp/test_file"
  register: testing

- name: enable SSH
  systemd:
    state: started
    name: sshd
    enabled: yes
  # This is used as a workaround for our test harness using Docker
  # This way we can test quickly and efficiently, instead of spinning up a VM every time
  when: not testing.stat.exists

- name: Disable firewalld
  service:
    name: firewalld
    enabled: no
  # This is also ignored when testing in Docker
  when: not testing.stat.exists


- name: Install common
  dnf:
    name: ['git', 'git-lfs',  'jq', 'gcc', 'gcc-c++', 'kernel-devel', 'nmap',
    'screen', 'python-pip', 'vim-enhanced', 'python3-libselinux', 'zlib-devel',
    'golang', 'aria2', 'binwalk', 'ruby-devel', 'remmina',
    'fedora-workstation-repositories']

- name: Enable Google Chrome in Fedora-Workstation-Repositories
  dnf:
    name: google-chrome
    enablerepo: google-chrome
    state: present

- name: Install Chrome
  dnf:
    name: ['google-chrome-stable']

- name: Add gobins to PATH
  lineinfile:
    path: "~/.bashrc"
    line: "export PATH=~/go/bin:$PATH"
    regexp: "PATH=~\/go\/bin"
  become: no

- name: Alias vi to vim (privileged)
  lineinfile:
    path: /root/.bashrc
    line: "alias vi=vim"

- name: Alias vi to vim (unprivileged)
  lineinfile:
    path: ~/.bashrc
    line: "alias vi=vim"
  become: no

- name: Check if already installed
  command: ls -alh ~/go/bin/cgasm
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no
  become: no

- name: Install cgasm
  shell: go get github.com/bnagy/cgasm
  become: no
  when: is_installed.rc == 2
  tags: # We use this because we *need* a shell command here
    - skip_ansible_lint

- name: Check if already installed
  command: ls -alh ~/go/bin/glugger
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no
  become: no

- name: Install glugger
  command: go get github.com/zxsecurity/glugger
  become: no
  when: is_installed.rc == 2

- name: Install python things
  pip:
    name: ['speedtest-cli', 'dnspython']

- name: Set time to AEST
  timezone:
    name: Australia/Melbourne

- name: ensure /usr/src exists
  file: path=/usr/src state=directory mode=0644

- name: clone bash_it
  git: repo=https://github.com/Bash-it/bash-it.git dest=/usr/src/Bash_it depth=1

- name: bash_it check (root)
  command: ls -alh /root/.bash_it
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no

- name: copy bash_it (root)
  shell: cp -r /usr/src/Bash_it ~/.bash_it
  when: is_installed.rc == 2
  tags: # We use this because we *need* a shell command here
    - skip_ansible_lint

- name: install bash_it (root)
  shell: ~/.bash_it/install.sh --silent
  when: is_installed.rc == 2
  tags: # We use this because we *need* a shell command here
    - skip_ansible_lint

- name: bash_it check (non-root)
  command: ls -alh ~/.bash_it
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no
  become: no
  tags: # We use this because we *need* a shell command here
    - skip_ansible_lint

- name: copy bash_it (non-root)
  shell: cp -f -r /usr/src/Bash_it ~/.bash_it
  when: is_installed.rc == 2
  become: no
  tags: # We use this because we *need* a shell command here
    - skip_ansible_lint

- name: bash_it install (non-root)
  shell: ~/.bash_it/install.sh --silent
  when: is_installed.rc == 2
  become: no
  tags: # We use this because we *need* a shell command here
    - skip_ansible_lint

- name: ensure .vim exists (non-root)
  file:
    path: ~/.vim
    state: directory
    mode: 0644
  become: no

- name: clone vim-polyglot
  git:
    repo: https://github.com/sheerun/vim-polyglot.git
    dest: /usr/src/vim-polyglot
    depth: 1
  register: vimpolyglot

- name: vim-polyglot (non-root)
  shell: "{{ item }}"
  with_items:
    - mkdir -p ~/.vim/pack/plugins/start/vim-polyglot
    - cp -r /usr/src/vim-polyglot/* ~/.vim/
  when: vimpolyglot.changed
  become: no
  tags: # We use this because we *need* a shell command here
    - skip_ansible_lint

- name: ensure .vim exists (root)
  file:
    path: ~/.vim
    state: directory
    mode: 0644

- name: vim-polyglot (root)
  shell: "{{ item }}"
  with_items:
    - mkdir -p ~/.vim/pack/plugins/start/vim-polyglot
    - cp -r /usr/src/vim-polyglot/* ~/.vim/
  when: vimpolyglot.changed
  tags: # We use this because we *need* a shell command here
    - skip_ansible_lint

- name: screen dotfile
  copy:
    src: files/.screenrc
    dest: ~/.screenrc
    mode: 0644
  become: no

- name: install nodejs
  dnf: name="nodejs"

- name: vte config (regular user)
  lineinfile:
    path: ~/.bashrc
    insertafter: "^#!/usr/bin/env"
    line: ". /etc/profile.d/vte.sh"
  become: no

- name: vte config (root)
  lineinfile:
    path: ~/.bashrc
    insertafter: "^#!/usr/bin/env"
    line: ". /etc/profile.d/vte.sh"

- name: Change theme from bobby to sexy (root)
  replace:
    path: ~/.bashrc
    regexp: bobby
    replace: sexy

- name: Change theme from bobby to sexy (default user)
  replace:
    path: ~/.bashrc
    regexp: bobby
    replace: sexy
  become: no
