---
- name: enable SSH
  systemd:
    state: started
    name: sshd
    enabled: yes

- name: Disable firewalld
  service:
    name: firewalld
    enabled: no

- name: Install common
  dnf: 
    name: ['git', 'jq', 'gcc', 'gcc-c++', 'kernel-devel', 'nmap', 'screen', 'python-pip', 'vim-enhanced', 'libselinux-python', 'zlib-devel', 'golang', 'aria2', 'binwalk', 'ruby-devel', 'remmina', 'fedora-workstation-repositories']

- name: Enable Google Chrome in Fedora-Workstation-Repositories
  dnf:
    name: google-chrome
    enablerepo: google-chrome
    state: present

- name: Install Chrome
  dnf: 
    name: ['google-chrome-stable']

- lineinfile:
    path: ~/.bashrc
    line: "export PATH=~/go/bin:$PATH"
  become: no

- lineinfile:
    path: ~/.bashrc
    line: "alias vi=vim"

- lineinfile:
    path: ~/.bashrc
    line: "alias vi=vim"
  become: no

- name: Check if already installed
  command: ls -alh /home/$USER/go/bin/cgasm
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no
  become: no

- name: Install cgasm
  shell: go get github.com/bnagy/cgasm
  become: no
  when: is_installed.rc == 2

- name: Check if already installed
  command: ls -alh /home/$USER/go/bin/glugger
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no
  become: no

- name: Install glugger
  shell: go get github.com/zxsecurity/glugger
  become: no
  when: is_installed.rc == 2


- name: Install python things
  pip:
    name: ['speedtest-cli', 'dnspython']

- name: Set time to AEST
  timezone: 
    name: Australia/Melbourne

- name: ensure /usr/src exists
  file: path=/usr/src state=directory

- name: clone bash_it
  git: repo=https://github.com/Bash-it/bash-it.git dest=/usr/src/Bash_it depth=1

- name: bash_it check (root)
  command: ls -alh /root/.bash_it
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no

- name: copy bash_it (root)
  shell: cp -r /usr/src/Bash_it ~/.bash_it
  when: is_installed.rc == 2
  
- name: install bash_it (root)
  shell: ~/.bash_it/install.sh --silent
  when: is_installed.rc == 2

- name: bash_it check (non-root)
  command: ls -alh ~/.bash_it
  register: is_installed
  failed_when: is_installed.rc > 2
  changed_when: no
  become: no

- name: copy bash_it (non-root)
  shell: cp -f -r /usr/src/Bash_it ~/.bash_it
  when: is_installed.rc == 2
  become: no

- name: bash_it install (non-root)
  shell: ~/.bash_it/install.sh --silent
  when: is_installed.rc == 2
  become: no

- name: ensure .vim exists (non-root)
  file:
    path: ~/.vim
    state: directory
  become: no

- name: clone vim-polyglot
  git: repo=https://github.com/sheerun/vim-polyglot.git dest=/usr/src/vim-polyglot depth=1

- name: vim-polyglot (non-root)
  shell: cp -r /usr/src/vim-polyglot/* ~/.vim/
  when: is_installed.rc == 2
  become: no

- name: ensure .vim exists (root)
  file:
    path: ~/.vim
    state: directory

- name: vim-polyglot (root)
  shell: cp -r /usr/src/vim-polyglot/* ~/.vim/
  when: is_installed.rc == 2

- name: screen dotfile
  copy:
    src: files/.screenrc
    dest: ~/.screenrc
  become: no

- name: install nodejs
  dnf: name="nodejs"

- lineinfile:
    path: ~/.bashrc
    insertafter: "^#!/usr/bin/env"
    line: ". /etc/profile.d/vte.sh"
  become: no

- lineinfile:
    path: ~/.bashrc
    insertafter: "^#!/usr/bin/env"
    line: ". /etc/profile.d/vte.sh"

- name: Change theme from bobby to sexy (root)
  replace:
    path: ~/.bashrc
    regexp: bobby
    replace: sexy

- name: Change theme from bobby to sexy (default user)
  replace:
    path: ~/.bashrc
    regexp: bobby
    replace: sexy
  become: no
