---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/fedora:35
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: ansible
