---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: stat /usr/bin/code
    stat:
      path: /usr/bin/code
    register: stat_result
  - name: Assert `code` binary exists
    assert:
      that: stat_result.stat.exists 