---
- name: Register testing file
  stat:
    path: "/tmp/test_file"
  register: testing

- name: Install prereqs
  dnf:
    name: [ 'gnuplot', 'libtool', 'make', 'automake', 'bison', 'glib2', 'glib2-devel', 'msgpack-devel']

- name: Download and unpack
  unarchive:
    src: http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz
    dest: /usr/src/
    remote_src: yes
    mode: 0644
  register: u

- name: Compile and install
  command: "chdir=/usr/src/afl-2.52b/ {{ item }}"
  with_items:
    - make
    - make install
  when: u.changed

- name: core deumps plz
  shell: echo core > /proc/sys/kernel/core_pattern
  # "testing" is what we use when testing the playbook with end to end
  # when it's being 'tested'. it's in a docker container and /proc/sys is read-only
  when: not testing.stat.exists