---
- name: Install prereqs
  dnf: name={{ item }}
  with_items:
   - cmake
   - make
   - git
   - python2
   - binutils
   - libgcc
   - glibc-devel
   - glibc-devel.i686
   - ninja-build

- name: Grab latest LLVM
  git:
    repo: http://llvm.org/git/llvm.git
    dest: /usr/src/llvm
    depth: 1
  register: grabbed

- name: Grab latest Clang
  git:
    repo: http://llvm.org/git/clang.git
    dest: /usr/src/llvm/tools/clang
    depth: 1
  when: grabbed.changed
  register: grabbed

- name: Grab latest Compiler-RT (ASAN, etc)
  git:
    repo: http://llvm.org/git/compiler-rt.git
    dest: /usr/src/llvm/projects/compiler-rt
    depth: 1
  when: grabbed.changed
  register: grabbed

- name: Grab latest libcxx
  git:
    repo: http://llvm.org/git/libcxx.git
    dest: /usr/src/llvm/projects/libcxx
    depth: 1
  when: grabbed.changed
  register: grabbed

- name: Grab latest libxxabi
  git:
    repo: http://llvm.org/git/libcxxabi.git
    dest: /usr/src/llvm/projects/libcxxabi
    depth: 1
  when: grabbed.changed
  register: grabbed

- name: Grab latest clang-tools
  git:
    repo: http://llvm.org/git/clang-tools-extra.git 
    dest: /usr/src/llvm/tools/clang/extra
    depth: 1
  when: grabbed.changed
  register: grabbed

- name: Create build folder
  command: " {{ item }} chdir=/usr/src/"
  with_items:
    - mkdir -p llvm-build
  when: grabbed.changed

- name: Compile and install
  command: " {{ item }} chdir=/usr/src/llvm-build/"
  with_items:
    - cmake -G "Ninja" -DLIBCXX_ENABLE_SHARED=OFF -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86" ../llvm
    - ninja 
    - ninja install
  when: grabbed.changed

- name: Remove temp files
  command: "rm -rf /usr/src/llvm-build/*"
  when: grabbed.changed
