---
name: common
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install podman -y
          sudo  python3 -m pip install "molecule[lint,podman]"
      - name: Test with molecule
        run: |
          cd roles/common && molecule test